// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSddl10eZG6CckA3XbDO_1Me1Zu26qV2g',
    appId: '1:697305901685:web:35df9be44bb237497ca63c',
    messagingSenderId: '697305901685',
    projectId: 'track2-auth-app-9921',
    authDomain: 'track2-auth-app-9921.firebaseapp.com',
    storageBucket: 'track2-auth-app-9921.firebasestorage.app',
    measurementId: 'G-97J1Y8KZHV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZJpj-ECUJMHxBAWw-6hAY6ZyThxGYJhI',
    appId: '1:697305901685:android:225a5187d8a79ced7ca63c',
    messagingSenderId: '697305901685',
    projectId: 'track2-auth-app-9921',
    storageBucket: 'track2-auth-app-9921.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX-Qx9BTdcjVrLbBrnQv0HQnubSaztVfg',
    appId: '1:697305901685:ios:20d60252c1e515b27ca63c',
    messagingSenderId: '697305901685',
    projectId: 'track2-auth-app-9921',
    storageBucket: 'track2-auth-app-9921.firebasestorage.app',
    iosBundleId: 'com.example.authAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX-Qx9BTdcjVrLbBrnQv0HQnubSaztVfg',
    appId: '1:697305901685:ios:20d60252c1e515b27ca63c',
    messagingSenderId: '697305901685',
    projectId: 'track2-auth-app-9921',
    storageBucket: 'track2-auth-app-9921.firebasestorage.app',
    iosBundleId: 'com.example.authAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSddl10eZG6CckA3XbDO_1Me1Zu26qV2g',
    appId: '1:697305901685:web:0740150c8d79ffb67ca63c',
    messagingSenderId: '697305901685',
    projectId: 'track2-auth-app-9921',
    authDomain: 'track2-auth-app-9921.firebaseapp.com',
    storageBucket: 'track2-auth-app-9921.firebasestorage.app',
    measurementId: 'G-NFCWGE7YZE',
  );
}
